services:
  mysqldb:
    image: mysql:8.0
    container_name: zdrco-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: zdrco-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysqldb

volumes:
  db_data: